sudo: required
dist: trusty
language: node_js
node_js:
  - '7'
cache:
  directories:
    - "node_modules"
addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- npm install -g angular-cli
- npm install
- npm run build
- npm run lint

script: 
- npm test
- npm run e2e