sudo: required
dist: trusty
language: node_js
node_js:
  - '7'
cache:
  directories:
    - "node_modules"
addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- npm install

script:
- npm run lint 
- npm run build
- npm test
- npm run e2e

before_deploy:
- npm run build

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "$FIREBASE_TOKEN"
  on:
    branch: master